/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "surface-tint": "#c6c6c7",
        "primary-fixed-dim": "#c6c6c7",
        "on-error-container": "#ffdad6",
        "outline-variant": "#242424",
        "background": "#050505",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-container": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
        "on-surface-variant": "#A8A8A8",
        "secondary-container": "#484949",
        "primary": "#ffffff",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-variant": "#353434",
        "surface": "#141313",
        "error": "#ffb4ab",
        "surface-container": "#111111",
        "surface-container-high": "#1a1a1a",
        "on-secondary-container": "#b8b8b8",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-highest": "#353434",
        "secondary-fixed": "#e3e2e2",
        "on-primary-container": "#636565",
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary": "#2f3131",
        "on-secondary": "#2f3131",
        "on-tertiary-fixed-variant": "#454747",
        "surface-container-low": "#0C0C0C",
        "secondary-fixed-dim": "#c7c6c6",
        "on-primary-fixed-variant": "#454747",
        "inverse-on-surface": "#313030",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "secondary": "#c7c6c6",
        "on-tertiary-container": "#636565",
        "tertiary": "#ffffff",
        "on-primary": "#050505",
        "surface-bright": "#3a3939",
        "inverse-primary": "#5d5f5f",
        "surface-dim": "#141313",
        "outline": "#242424",
        "on-secondary-fixed-variant": "#464747",
        "surface-container-lowest": "#050505",
        "on-secondary-fixed": "#1a1c1c",
        "primary-container": "#e2e2e2"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      spacing: {
        "panel-padding": "24px",
        "stack-lg": "32px",
        "unit": "4px",
        "margin-page": "48px",
        "stack-md": "16px",
        "gutter": "1px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "body-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Chivo", "sans-serif"],
        "headline-md": ["Chivo", "sans-serif"],
        "data-display": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Chivo", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "400" }],
        "headline-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "data-display": ["32px", { "lineHeight": "1", "letterSpacing": "-0.05em", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
